find_package(argparse CONFIG REQUIRED)
find_package(directx-dxc CONFIG REQUIRED)
find_package(directxmath CONFIG REQUIRED)
find_package(glaze CONFIG REQUIRED)
find_package(imgui CONFIG REQUIRED)
find_package(SDL2 CONFIG REQUIRED)
find_package(spdlog CONFIG REQUIRED)
find_package(vk-bootstrap CONFIG REQUIRED)
find_package(Vulkan REQUIRED)
find_package(VulkanHeaders CONFIG REQUIRED)
find_package(VulkanMemoryAllocator CONFIG REQUIRED)
find_package(VulkanMemoryAllocator-Hpp CONFIG REQUIRED)

include(${CMAKE_CURRENT_LIST_DIR}/vulkan-hpp-module.cmake)