set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	set(CMAKE_CROSSCOMPILING OFF CACHE BOOL "")
endif ()

set(TARGET "x86_64-w64-mingw32")
set(CMAKE_C_COMPILER_TARGET ${TARGET})
set(CMAKE_CXX_COMPILER_TARGET ${TARGET})

set(COMPILER_ARGS
	"--start-no-unused-arguments"
	"-gcodeview"
	"--end-no-unused-arguments"
	"-ferror-limit=0"
	"-fms-extensions"
	"-fms-hotpatch"
)

set(CMAKE_C_COMPILER
	"${TARGET}-clang${CMAKE_HOST_EXECUTABLE_SUFFIX}"
	${COMPILER_ARGS}
)
set(CMAKE_CXX_COMPILER
	"${TARGET}-clang++${CMAKE_HOST_EXECUTABLE_SUFFIX}"
	${COMPILER_ARGS}
)
set(CMAKE_ASM_COMPILER
	"${TARGET}-clang${CMAKE_HOST_EXECUTABLE_SUFFIX}"
	${COMPILER_ARGS}
)
set(CMAKE_RC_COMPILER
	"llvm-rc${CMAKE_HOST_EXECUTABLE_SUFFIX}"
)

set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

include("${CMAKE_CURRENT_LIST_DIR}/clang-windows-common.cmake")
