set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	set(CMAKE_CROSSCOMPILING OFF CACHE BOOL "")
	set(EXECUTABLE_SUFFIX ".exe")
endif ()

set(COMPILER_ARGS
	"-g"
	"-ferror-limit=0"
)

set(CMAKE_C_COMPILER
	"C:/Program Files/LLVM/bin/clang${EXECUTABLE_SUFFIX}"
	${COMPILER_ARGS}
)
set(CMAKE_CXX_COMPILER
	"C:/Program Files/LLVM/bin/clang++${EXECUTABLE_SUFFIX}"
	${COMPILER_ARGS}
)
set(CMAKE_ASM_COMPILER
	"C:/Program Files/LLVM/bin/clang${EXECUTABLE_SUFFIX}"
	${COMPILER_ARGS}
)
set(CMAKE_RC_COMPILER
	"C:/Program Files/LLVM/bin/llvm-rc${EXECUTABLE_SUFFIX}"
)

set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "Embedded")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug,RTC>:Debug>DLL")
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

include("${CMAKE_CURRENT_LIST_DIR}/clang-windows-common.cmake")
